### ISSUE TITLE
Year 2038 problem

### ISSUE THREAD

**Issue by echipachenko** [enioka-Haute-Couture/jqm#361]
Hi @marcanpilami 
We noticed that you use TIMESTAMP(3) data type in tables, it can cause year 2038 problem https://en.wikipedia.org/wiki/Year_2038_problem (type overflow)

Please update data types in DB and API

Right now it's not possible to set RunAfter parameter after 2039 year

**Comment by Pauleing** [comment]
We now use TIMESTAMP(8).
