### ISSUE TITLE
Incoherent dates in tables

### ISSUE THREAD

**Issue by deiv** [enioka-Haute-Couture/jqm#393]
Hi,

Looking at the dates fields in the tables **history** and **job_instance**, I see some incoherencies:

- table history:

```
status,date_enqueue,date_start,date_end
ENDED,2020-03-11 12:24:36.499000,2020-03-11 11:25:31.820000,2020-03-11 11:25:32.759000
ENDED,2020-03-11 12:24:36.341000,2020-03-11 11:25:30.734000,2020-03-11 11:25:31.439000
ENDED,2020-03-11 12:24:36.184000,2020-03-11 11:25:30.733000,2020-03-11 11:25:31.448000
```

for the column **date_enqueue** seems that the time is one hour ahead than the **date_start** and **date_end** columns. Maybe **date_enqueue** is local time and the others UTC ?

- table  job_instance:

```
status,date_enqueue,date_start
SUBMITTED,2020-03-11 12:24:33.997297,null
SUBMITTED,2020-03-11 12:24:34.151378,null
RUNNING,2020-03-11 12:24:33.846363,2020-03-11 12:26:20.447387
```
The dates columns **date_enqueue** and **date_start** are in the same ""zone"", maybe local time?

For the sake of references, the jobs where launched around :

> Wed, 11 Mar 2020 12:24:49 +0100

**Comment by ffayel** [comment]
Same probleme : https://github.com/enioka/jqm/issues/400

**Comment by marcanpilami** [comment]
Hi - an issue of this type was recently solved for Oracle. What database are you using?

**Comment by deiv** [comment]
@marcanpilami postgresql

**Comment by oliver3Datax** [comment]
i am still facing this issue, the enqueueing time runs 1 hour in advance, see screenshot below:
![image](https://user-images.githubusercontent.com/111345328/199452577-4f99368d-76bf-44fa-9bec-96b29516eaec.png)
