### ISSUE TITLE
Error when insert in job_instance

### ISSUE THREAD

**Issue by opgimenez** [enioka-Haute-Couture/jqm#495]
Hi, 
First of all, sorry about my english, i'm trying to explain my problem better as possible.
I need to launch a JQM process from java, but when i call to JqmClientFactory.getClient().enqueue(jd); i'm getting an error. 
The error is:
Caused by: java.sql.SQLException: Argumento(s) no válido(s) en la llamada
Caused by: java.sql.SQLException: Not valid arguments

I know that the problem is when try to insert in JOB_INSTANCE table (oracle) because the parameters in values are 
[null, null, XX, XX, null, null, null, null, SUBMITTED, XXXX, XXX, XXX, **false**, **false**, null, XXX, RUN]

Those "falses" are the problem because references to fields HIGHLANDER and FROM_SCHEDULE on table, and those are numeric, when i try the insert directly in bbdd editor insert works well with 0 instead of false...
I try to change the library version... and not works

JQM version is 2.2.5

Any help please?

Thank you.

**Comment by Pauleing** [comment]
Not reproducible. Please reopen if it occurs again.
