### ISSUE TITLE
Routing table

### ISSUE THREAD

**Issue by ArnaudChirat** [enioka-Haute-Couture/jqm#530]
To allow an engine to call an other engine with DNS, a routing table should be done.
Routing table:
- IP: Address IP of the engine
- ID: the engine ID

The range can be calculated easily so no need to stock the information.

A set of api should be done:

- GetEngineRouteByJobId
- CRUD on the table

**Comment by DaSpood** [comment]
> The range can be calculated easily so no need to stock the information.

It may be worth still storing that information in the table to simplify the logic surrounding the routing of requests.

**Comment by ArnaudChirat** [comment]
Finally no need to stock anything as it can be easily recalculated from the jobId
